# Goal
std_msgs/Header header
int8 request_type
string request_text
geometry_msgs/PoseStamped position
---
# Result
int8 state
string result_text
geometry_msgs/PoseStamped position
---
# Feedback
int8 state
int8 progress
string feedback_text
geometry_msgs/PoseStamped position